Problem - 1: Array Creation:

Complete the following Tasks:

In [ ]:
# 1. Initialize an empty array with size 2X2.
import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
# creates a 2x2 array without initializing its elements to any specific values

print("Empty Array (2x2): ", empty_array)

# 2. Initialize an all-one array with size 4X2.
ones_array = np.ones((4, 2))
# it creates an array with dimensions 4x2 where all elements are initialized to 1

print("\nAll-Ones Array (4x2): ", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value.
fill_value = 7 #assigns the value 7 to the variable fill_value
filled_array = np.full((3, 3), fill_value) # creates a 3x3 array where all
# elements are set to the value stored in fill_value (which is 7)

print("\nArray filled with value 7 (3x3): ", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array.
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
#creates a 2x3 array with the provided values & serves as a reference for the shape.
zeros_like_array = np.zeros_like(reference_array)
# creates a new array with the same shape (2x3) as reference_array but filled with zeros
print("\nZeros Array with similar shape as reference array: ", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(reference_array)
# this is similar to the previous step (#4)but instead of zeros,it creates an array
# filled with ones, using the shape of reference_array
print("\nOnes Array with similar shape as reference array: ", ones_like_array)

# 6. For an existing list, convert it to a NumPy array.
new_list = [1, 2, 3, 4]
# creates a standard Python list
numpy_array = np.array(new_list)
# converts this list into a NumPy array, making it suitable for numerical computations.
print("\nconverted list to NumPy Array: ", numpy_array)


Empty Array (2x2):  [[4.72374838e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]

All-Ones Array (4x2):  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with Value 7 (3x3):  [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Reference Array:  [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Reference Array:  [[1 1 1]
 [1 1 1]]

Converted List to NumPy Array:  [1 2 3 4]


In [ ]:
# 4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:

import numpy as np

# 1. Create an array with values ranging from 10 to 49.
array_range = np.arange(10, 50)
#np.arange() function to generate a sequence of numbers from range 10  to 50 and stores in array_range
print("Array with values ranging from 10 to 49:\n", array_range)

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
# creates an array from 0 to 8 &.reshape(3, 3)changes the shape of this array into a 3x3 matrix
print("\n3x3 Matrix with values ranging from 0 to 8:\n", matrix_3x3)

# 3. Create a 3X3 identity matrix.
identity_matrix = np.eye(3)
# np.eye(3) directly creates a matrix with 1s along the diagonal and 0s elsewhere (3x3 matrix) & stores in indentify matrix
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
# generates an array of 30 random numbers between 0 and 1.
mean_value = random_array.mean()
# .mean() calculates the average of the above numbers
print("\nRandom Array of Size 30:\n", random_array)
print("Mean of the Random Array:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
# This section creates a 10x10 matrix (random_matrix) filled with random numbers.
# .min() and .max() find the smallest and largest values in this matrix.
print("\n10x10 Array with Random Values:\n", random_matrix)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
# np.zeros(10) creates an array of 10 zeros.
zero_array[4] = 1  # Replace 5th element (index 4) with 1
print("\nZero Array with 5th Element Replaced by 1:\n", zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
# This reverses the order of elements in the list arr and stores the result
#  in reversed_array(Using slicing)
print("\nReversed Array:\n", reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside.
border_array = np.ones((5, 5))  # Example size: 5x5
border_array[1:-1, 1:-1] =
# This creates a 5x5 matrix (border_array) filled with 1s.
# Then, border_array[1:-1, 1:-1] = 0 sets the inner elements to 0, leaving a border of 1s.
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill odd rows, even columns
checkerboard[::2, 1::2] = 1  # Fill even rows, odd columns
# This generates an 8x8 matrix (checkerboard) filled with 0s.
# The next two lines use slicing to create a checkerboard pattern by
# assigning 1s to alternating elements.



print("\n8x8 Checkerboard Pattern:\n", checkerboard)





Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of Size 30:
 [0.89208566 0.30363675 0.55818788 0.39635008 0.72950849 0.38156397
 0.40280795 0.40754448 0.38552529 0.27817917 0.73593672 0.30882502
 0.88956888 0.64285121 0.04902413 0.90851114 0.83865261 0.82255881
 0.79369906 0.16810692 0.56057043 0.9957004  0.37690782 0.8188561
 0.58081697 0.44976879 0.43202927 0.55314732 0.11752397 0.98762927]
Mean of the Random Array: 0.5588691514644418

10x10 Array with Random Values:
 [[0.28186135 0.89729565 0.31046443 0.66625888 0.35600368 0.24900706
  0.44365487 0.7017191  0.99319582 0.24376846]
 [0.79751049 0.3812467  0.10204755 0.90747488 0.68290718 0.36242909
  0.7592426  0.37381613 0.73680289 0.82646361]
 [0.61742534 0.25475197 0.7180

In [ ]:
# Problem - 3: Array Operations:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:

import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# x and y are 2-dimensional arrays (matrices) with two rows and two columns each.
# v and w are 1-dimensional arrays (vectors) with two elements each.


# here are some  basic array operations below :

# 1. Add the two arrays
array_sum = x + y
print("Sum of x and y:\n", array_sum)

# 2. Subtract the two arrays
array_diff = x - y
print("\nDifference of x and y:\n", array_diff)

# 3. Multiply the array with any integer (e.g., multiply by 3)
array_scaled = x * 3
print("\nArray x multiplied by 3:\n", array_scaled)

# 4. Find the square of each element in the array
array_squared = x ** 2
print("\nSquare of each element in x:\n", array_squared)

# 5. Find the dot product between v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
print("\nDot product of v and w:", dot_vw)
dot_xv = np.dot(x, v)
print("\nDot product of x and v:\n", dot_xv)
dot_xy = np.dot(x, y)
print("\nDot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows, and v and w along columns
# along rows
concat_xy_row = np.concatenate((x, y), axis=0) #to join two arrays together
print("\nConcatenation of x and y along rows:\n", concat_xy_row)

# along columns
concat_vw_col = np.vstack((v, w)).T  # Stack vertically and transpose for column concat
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v: if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempt to concatenate along rows
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError during concatenation of x and v:", e)

# I got an error because v and x didn't have matching dimensions
# Fixing the error by reshaping v to match x's dimensions
v_reshaped = v[np.newaxis, :]  # Reshape v to (1, 2)
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\nConcatenation of x and reshaped v:\n", concat_xv_fixed)

Sum of x and y:
 [[ 6  8]
 [10 13]]

Difference of x and y:
 [[-4 -4]
 [-4 -3]]

Array x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

Error during concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Concatenation of x and reshaped v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
# Problem - 4: Matrix Operations:
# • For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:

import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I (Identity Matrix)
# Inverse of A
A_inv = np.linalg.inv(A)


# A . A⁻¹
result = np.dot(A, A_inv)

print("A * A⁻¹:\n", result)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)

# Check if AB = BA
is_equal = np.array_equal(AB, BA)
print("\nIs AB equal to BA? ", is_equal)

# 3. Prove (AB)ᵀ = BᵀAᵀ

# (AB)ᵀ
AB_transpose = np.transpose(AB)

#Bᵀ and Aᵀ
BT = np.transpose(B)
AT = np.transpose(A)

# BᵀAᵀ
BT_AT = np.dot(BT, AT)

print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)

# Check if (AB)ᵀ = BᵀAᵀ
is_transpose_equal = np.array_equal(AB_transpose, BT_AT)
print("\nIs (AB)ᵀ equal to BᵀAᵀ? ", is_transpose_equal)

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA?  False

(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

Is (AB)ᵀ equal to BᵀAᵀ?  True


In [ ]:
# Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Step 1: Determinant of A
det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))

print("Determinant of A:", det_A)

# Step 2: Cofactor matrix
cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])

# Step 3: Adjoint of A (transpose of cofactor matrix)
adjoint_A = cofactor_matrix.T

# Step 4: Inverse of A
inverse_A = adjoint_A / det_A
print("\nInverse of A:\n", inverse_A)

# Step 5: X = A⁻¹B
X = np.dot(inverse_A, B)
print("\nSolution (x, y, z):", X)


In [ ]:
# Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Inverse of A using np.linalg.inv
A_inv = np.linalg.inv(A)

# X = A⁻¹B
X = np.dot(A_inv, B)

print("Inverse of A:\n", A_inv)
print("\nSolution (x, y, z):", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
# 4.2 Experiment: How Fast is Numpy?
# In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays.
#Follow the instructions:

import time

# 1. Element-wise Addition:
print("1. Element-wise Addition")

# Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds\n")

1. Element-wise Addition
Time taken by Python Lists: 0.18648 seconds
Time taken by numpy: 0.00732 seconds



In [ ]:
# 2. Element-wise Multiplication
print("2. Element-wise Multiplication")

# Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds\n")


2. Element-wise Multiplication
Time taken by Python Lists: 0.30713 seconds
Time taken by numpy: 0.00859 seconds



In [ ]:
# 3. Dot Product
print("3. Dot Product")

# Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds\n")

3. Dot Product
Time taken by Python Lists: 0.14520 seconds
Time taken by numpy: 0.00250 seconds



In [ ]:
# 4. Matrix Multiplication
print("4. Matrix Multiplication")
size = 100

# Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[j for j in range(size)] for _ in range(size)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds")

4. Matrix Multiplication
Time taken by Python Lists: 0.16055 seconds
Time taken by numpy: 0.00142 seconds
